version: '3'
services:
  db:
    image: "mysql:5.7"
    volumes:
      - ./mockdb:/var/lib/mysql:z
    ports:
      - "33060:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "admin"
    tty: true

